{
 "title": "ftdc_dashboard",
 "time": { "from": "2024-05-25T19:23:09.607Z", "to": "2031-05-26T00:01:28.240Z" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.bucket,\n    tag: \"hostname\"\n)"
    }
   },
   {
    "name": "version",
    "label": "version",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.bucket,\n    tag: \"version\"\n)"
    }
   }
  ]
 },
 "panels": [
  { "title": "WiredTiger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WiredTiger Tickets / Active Clients",
   "type": "timeseries",
   "description": "Tickets Available Read displays the number of read tickets available to the WiredTiger storage engine. Read tickets represent the number of concurrent read operations allowed into the storage engine. When this value reaches zero, new read requests might queue until a read ticket becomes available.\n\nTickets Available Write displays the number of write tickets available to the WiredTiger storage engine. Write tickets represent the number of concurrent write operations allowed into the storage engine. When this value reaches zero, new write requests might queue until a write ticket becomes available.",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.wiredTiger.concurrentTransactions.write.available\" \n                    or r[\"_field\"] == \"serverStatus.wiredTiger.concurrentTransactions.read.available\"\n                    or r[\"_field\"] == \"serverStatus.globalLock.activeClients.writers\"\n                    or r[\"_field\"] == \"serverStatus.globalLock.activeClients.readers\")\n  |> map(fn: (r) => ({r with _field: \n    if r._field == \"serverStatus.wiredTiger.concurrentTransactions.write.available\" then \"write tickets avail\"\n    else if r._field == \"serverStatus.wiredTiger.concurrentTransactions.read.available\" then \"read tickets avail\"\n    else if r._field == \"serverStatus.globalLock.activeClients.writers\" then \"active writers\"\n    else if r._field == \"serverStatus.globalLock.activeClients.readers\" then \"active readers\"\n    else r._field\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "WiredTiger cache",
   "type": "timeseries",
   "description": "used displays the total bytes cached in memory for serving reads and writes.\n\nThese metrics include both indexes and data from the working set.\n\nSustained high cache usage indicates the RAM is too small for your workloads. Optimize your queries to avoid frequent disk reads. If write operations make cache usage high, throttle them.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r[\"_field\"] == \"serverStatus.wiredTiger.cache.maximum bytes configured\"  or r[\"_field\"] == \"serverStatus.wiredTiger.cache.bytes currently in the cache\" )\r\n  |> map(fn: (r) => ({ r with _value: r._value / 1024 / 1024 / 1024}))\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.wiredTiger.cache.maximum bytes configured\" then \"max configured\"\r\n    else if r._field == \"serverStatus.wiredTiger.cache.bytes currently in the cache\" then \"in cache\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Bytes read into / written from cache",
   "type": "timeseries",
   "description": "read Into displays the rate in bytes per second of data read from disk into memory to service queries.\n\nwritten From  displays the rate in bytes per second of data written from memory into disk to service writes.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r[\"_field\"] == \"serverStatus.wiredTiger.cache.bytes written from cache\" or r[\"_field\"] == \"serverStatus.wiredTiger.cache.bytes read into cache\")\r\n  |> derivative(unit: 1s)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.wiredTiger.cache.bytes written from cache\" then \"written from cache\"\r\n    else if r._field == \"serverStatus.wiredTiger.cache.bytes read into cache\" then \"read into cache\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Pages Evicted",
   "type": "timeseries",
   "description": "Clean vs dirty data\n\nClean refers to data in the cache that is identical to the version stored on disk.\nDirty refers to data in the cache that has been modified and needs to be reconciled with the data stored on the disk.\n\nClean vs dirty eviction\n\nIn the case of clean eviction, there is no dirty content on the page and it is directly removed from the memory. After that, the page remains solely on the disk unchanged.\nIn the case of dirty eviction, the dirty page goes through reconciliation. The obsolete content on the page is thrown out, the latest value goes to the data store and older values go to the history store.",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.wiredTiger.cache.modified pages evicted\" or r[\"_field\"] == \"serverStatus.wiredTiger.cache.unmodified pages evicted\")\r\n  |> map(fn: (r) => ({ r with _value: r._value }))\r\n  |> derivative(unit: 1s)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.wiredTiger.cache.modified pages evicted\" then \"modified\"\r\n    else if r._field == \"serverStatus.wiredTiger.cache.unmodified pages evicted\" then \"unmodified\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Dirty bytes in the cache",
   "type": "timeseries",
   "description": "indicates modified data that needs to be written to the data files via a checkpoint.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.wiredTiger.cache.tracked dirty bytes in the cache\")\n  |> map(fn: (r) => ({r with _field: \"dirty bytes\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Mb written for checkpoint",
   "type": "timeseries",
   "description": "A checkpoint is a known point in time from which WiredTiger can recover in the event of a crash or unexpected shutdown.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.wiredTiger.block-manager.bytes written for checkpoint\")\r\n  |> map(fn: (r) => ({r with _field: \"bytes written for checkpoint\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "wiredTiger Block Manager",
   "type": "timeseries",
   "description": "The WiredTiger block manager subsystem manages the reading and writing of data from the disk. It is designed to facilitate high performance, economic use of disk space and customizability.",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>   r[\"_field\"] == \"serverStatus.wiredTiger.block-manager.bytes read\" or r[\"_field\"] == \"serverStatus.wiredTiger.block-manager.bytes written\" )\r\n  |> map(fn: (r) => ({ r with _value: r._value}))\r\n  |> map(fn: (r) => ({ r with _value: r._value / 1024 /1024 }))\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.wiredTiger.block-manager.bytes read\" then \"bytes read\"\r\n    else if r._field == \"serverStatus.wiredTiger.block-manager.bytes written\" then \"bytes written\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s)\r\n",
     "legendFormat": "{{_field}}"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:CurrEstab\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "legendFormat": "TCP Established"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:CurrEstab\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "legendFormat": "TCP Established"
    }
   ]
  },
  {
   "title": "WiredTiger Data Handle",
   "type": "timeseries",
   "description": "A WiredTiger Data Handle (dhandle) is a generic representation of any named data source. This representation contains information such as its name, how many references there are to it, individual data source statistics and what type of underlying data object it is.\n\nWiredTiger maintains all dhandles in a global dhandle list accessed from the connection. Multiple sessions access this list, which is protected by a R/W lock. Each session also maintains a session dhandle cache which is a cache of dhandles a session has operated upon. The entries in the cache are references into the global dhandle list.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.wiredTiger.data-handle.connection data handles currently active\")\r\n  |> map(fn: (r) => ({r with _field: \"active data handles\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n  |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.connections.active\"\r\n                    or r[\"_field\"] == \"serverStatus.connections.current\"\r\n                    or r[\"_field\"] == \"serverStatus.connections.available\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.connections.active\" then \"active\"\r\n    else if r._field == \"serverStatus.connections.current\" then \"current\"\r\n    else if r._field == \"serverStatus.connections.available\" then \"available\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "legendFormat": "{{_field}}"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.connections.totalCreated\")\r\n  |> map(fn: (r) => ({r with _field: \"totalCreated\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.mem.virtual\" or r[\"_field\"] == \"serverStatus.mem.resident\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.mem.virtual\" then \"virtual\"\r\n    else if r._field == \"serverStatus.mem.resident\" then \"resident\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: 1m, fn: median, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))\r\n  |> yield(name: \"median\")\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.extra_info.page_faults\")\r\n  |> derivative(unit: v.windowPeriod)\r\n    |> map(fn: (r) => ({r with _field: \"page_faults\"}))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Network requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.network.numRequests\")\r\n  |> derivative(unit: v.windowPeriod)\r\n    |> map(fn: (r) => ({r with _field: \"numRequests\"}))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.opLatencies.reads.latency\" or r[\"_field\"] == \"serverStatus.opLatencies.writes.latency\" or r[\"_field\"] == \"serverStatus.opLatencies.commands.latency\"  )\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.opLatencies.reads.latency\" then \"reads\"\r\n    else if r._field == \"serverStatus.opLatencies.writes.latency\" then \"writes\"\r\n    else if r._field == \"serverStatus.opLatencies.commands.latency\" then \"commands\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => \r\n      r[\"_field\"] == \"serverStatus.opcounters.update\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.query\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.insert\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.getmore\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.delete\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.command\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.opcounters.update\" then \"update\"\r\n    else if r._field == \"serverStatus.opcounters.query\" then \"query\"\r\n    else if r._field == \"serverStatus.opcounters.insert\" then \"insert\"\r\n    else if r._field == \"serverStatus.opcounters.getmore\" then \"getmore\"\r\n    else if r._field == \"serverStatus.opcounters.delete\" then \"delete\"\r\n    else if r._field == \"serverStatus.opcounters.command\" then \"command\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Replica members lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] =~ /replSetGetStatus\\.members\\.\\d+\\.lastAppliedWallTime|serverStatus\\.localTime/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      member_0: if exists r[\"replSetGetStatus.members.0.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.0.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_1: if exists r[\"replSetGetStatus.members.1.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.1.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_2: if exists r[\"replSetGetStatus.members.2.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.2.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_3: if exists r[\"replSetGetStatus.members.3.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.3.lastAppliedWallTime\"])) / 1000.0 else 0.0,      // Add more members as needed\r\n  }))\r\n  |> yield(name: \"differences\")\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Replica members ping",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] =~ /replSetGetStatus\\.members\\.\\d+\\.pingMs/)\r\n  |> map(fn: (r) => ({r with _field: \"member_\" + strings.trimSuffix(v: strings.trimPrefix(v: r._field, prefix: \"replSetGetStatus.members.\"), suffix: \".pingMs\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Current Queue writers / readers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.globalLock.currentQueue.writers\" or r[\"_field\"] == \"serverStatus.globalLock.currentQueue.readers\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.globalLock.currentQueue.writers\" then \"writers\"\r\n    else if r._field == \"serverStatus.globalLock.currentQueue.readers\" then \"readers\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Replica members health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"replSetGetStatus.members.0.health\" or r[\"_field\"] == \"replSetGetStatus.members.1.health\" or r[\"_field\"] == \"replSetGetStatus.members.2.health\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"replSetGetStatus.members.0.health\" then \"member_0\"\r\n    else if r._field == \"replSetGetStatus.members.1.health\" then \"member_1\"\r\n    else if r._field == \"replSetGetStatus.members.2.health\" then \"member_2\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Query Executor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.queryExecutor.scannedObjects\" or r[\"_field\"] == \"serverStatus.metrics.queryExecutor.scanned\" or r[\"_field\"] == \"serverStatus.metrics.queryExecutor.collectionScans.total\")\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.metrics.queryExecutor.scannedObjects\" then \"scannedObjects\"\r\n    else if r._field == \"serverStatus.metrics.queryExecutor.scanned\" then \"scanned\"\r\n    else if r._field == \"serverStatus.metrics.queryExecutor.collectionScans.total\" then \"collectionScans\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Operations latencies op",
   "type": "timeseries",
   "description": "Operation latencies for the instance as a whole.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.opLatencies.reads.ops\" or r[\"_field\"] == \"serverStatus.opLatencies.writes.ops\" or r[\"_field\"] == \"serverStatus.opLatencies.commands.ops\" )\r\n  |> derivative(unit: 1s)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.opLatencies.reads.ops\" then \"reads\"\r\n    else if r._field == \"serverStatus.opLatencies.writes.ops\" then \"writes\"\r\n    else if r._field == \"serverStatus.opLatencies.commands.ops\" then \"commands\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r[\"_field\"] == \"serverStatus.uptime\" )\r\n  |> map(fn: (r) => ({r with _field: \"uptime\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n\r\n",
     "legendFormat": "{{_field}}"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.memory.SwapTotal_kb\" or r[\"_field\"] == \"systemMetrics.memory.SwapFree_kb\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, _field: \"Swap Used\", _value: (r[\"systemMetrics.memory.SwapTotal_kb\"] - r[\"systemMetrics.memory.SwapFree_kb\"]) * 1024 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.memory.SwapTotal_kb\" or r[\"_field\"] == \"systemMetrics.memory.SwapFree_kb\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, _field: \"Swap Used\", _value: (r[\"systemMetrics.memory.SwapTotal_kb\"] - r[\"systemMetrics.memory.SwapFree_kb\"]) * 1024 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "avg Obj Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"local.oplog.rs.stats.storageStats.avgObjSize\")\r\n  |> map(fn: (r) => ({r with _field: \"avgObjSize\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "FlowControl isLagged",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.flowControl.isLaggedTimeMicros\")\r\n  |> map(fn: (r) => ({r with _field: \"isLaggedTimeMicros\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> yield(name: \"last\")",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Asserts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.asserts.warning\" or r[\"_field\"] == \"serverStatus.asserts.user\" or r[\"_field\"] == \"serverStatus.asserts.rollovers\" or r[\"_field\"] == \"serverStatus.asserts.regular\" or r[\"_field\"] == \"serverStatus.asserts.msg\")\r\n  |> derivative(unit: v.windowPeriod)\r\n    |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.asserts.warning\" then \"warning\"\r\n    else if r._field == \"serverStatus.asserts.user\" then \"user\"\r\n    else if r._field == \"serverStatus.asserts.rollovers\" then \"rollovers\"\r\n    else if r._field == \"serverStatus.asserts.regular\" then \"regular\"\r\n    else if r._field == \"serverStatus.asserts.msg\" then \"msg\"\r\n    else r._field\r\n  }))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Opcounters Replica",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.opcountersRepl.command\" or r[\"_field\"] == \"serverStatus.opcountersRepl.delete\" or r[\"_field\"] == \"serverStatus.opcountersRepl.getmore\" or r[\"_field\"] == \"serverStatus.opcountersRepl.insert\" or r[\"_field\"] == \"serverStatus.opcountersRepl.query\" or r[\"_field\"] == \"serverStatus.opcountersRepl.update\")\r\n  |> derivative(unit: v.windowPeriod)\r\n    |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.opcountersRepl.command\" then \"command\"\r\n    else if r._field == \"serverStatus.opcountersRepl.delete\" then \"delete\"\r\n    else if r._field == \"serverStatus.opcountersRepl.getmore\" then \"getmore\"\r\n    else if r._field == \"serverStatus.opcountersRepl.insert\" then \"insert\"\r\n    else if r._field == \"serverStatus.opcountersRepl.query\" then \"query\"\r\n    else if r._field == \"serverStatus.opcountersRepl.update\" then \"update\"\r\n    else r._field\r\n  }))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.commands.createIndexes.total\" or r[\"_field\"] == \"serverStatus.metrics.commands.dataSize.total\" or r[\"_field\"] == \"serverStatus.metrics.commands.dropIndexes.total\" or r[\"_field\"] == \"serverStatus.metrics.commands.listCollections.total\" or r[\"_field\"] == \"serverStatus.metrics.commands.listDatabases.total\")\r\n|> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.metrics.commands.createIndexes.total\" then \"createIndexes\"\r\n    else if r._field == \"serverStatus.metrics.commands.dataSize.total\" then \"dataSize\"\r\n    else if r._field == \"serverStatus.metrics.commands.dropIndexes.total\" then \"dropIndexes\"\r\n    else if r._field == \"serverStatus.metrics.commands.listCollections.total\" then \"listCollections\"\r\n    else if r._field == \"serverStatus.metrics.commands.listDatabases.total\" then \"listDatabases\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.cursor.open.noTimeout\" or r[\"_field\"] == \"serverStatus.metrics.cursor.open.pinned\" or r[\"_field\"] == \"serverStatus.metrics.cursor.open.total\" or r[\"_field\"] == \"serverStatus.metrics.cursor.timedOut\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.metrics.cursor.open.noTimeout\" then \"open.noTimeout\"\r\n    else if r._field == \"serverStatus.metrics.cursor.open.pinned\" then \"open.pinned\"\r\n    else if r._field == \"serverStatus.metrics.cursor.open.total\" then \"open.total\"\r\n    else if r._field == \"serverStatus.metrics.cursor.timedOut\" then \"timedOut\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Documents (deleted / inserted / returned / updated)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.document.updated\" or r[\"_field\"] == \"serverStatus.metrics.document.returned\" or r[\"_field\"] == \"serverStatus.metrics.document.inserted\" or r[\"_field\"] == \"serverStatus.metrics.document.deleted\")\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.metrics.document.updated\" then \"updated\"\r\n    else if r._field == \"serverStatus.metrics.document.returned\" then \"returned\"\r\n    else if r._field == \"serverStatus.metrics.document.inserted\" then \"inserted\"\r\n    else if r._field == \"serverStatus.metrics.document.deleted\" then \"deleted\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Query Targeting: Scanned Objects / Returned ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>\r\n      r[\"_field\"] == \"serverStatus.metrics.document.returned\" or \r\n      r[\"_field\"] == \"serverStatus.metrics.queryExecutor.scannedObjects\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(\r\n      rowKey: [\"_time\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      scanned_returned_ratio: r[\"serverStatus.metrics.queryExecutor.scannedObjects\"] / r[\"serverStatus.metrics.document.returned\"]\r\n  }))\r\n  |> yield(name: \"scanned_returned_ratio\")\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Network In / Out physical",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.network.physicalBytesIn\" or r[\"_field\"] == \"serverStatus.network.physicalBytesOut\")\r\n  |> derivative(unit: 1s)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.network.physicalBytesIn\" then \"physicalBytesIn\"\r\n    else if r._field == \"serverStatus.network.physicalBytesOut\" then \"physicalBytesOut\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Network In / Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.network.bytesOut\" or r[\"_field\"] == \"serverStatus.network.bytesIn\")\r\n  |> map(fn: (r) => ({ r with _value: r._value / 1024 /1024 }))\r\n  |> derivative(unit: 1s)\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"serverStatus.network.bytesOut\" then \"bytesOut\"\r\n    else if r._field == \"serverStatus.network.bytesIn\" then \"bytesIn\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"local.oplog.rs.stats.storageStats.freeStorageSize\" or r[\"_field\"] == \"local.oplog.rs.stats.storageStats.storageSize\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"local.oplog.rs.stats.storageStats.freeStorageSize\" then \"free\"\r\n    else if r._field == \"local.oplog.rs.stats.storageStats.storageSize\" then \"storage\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r._field == \"systemMetrics.cpu.idle_ms\" or r._field == \"systemMetrics.cpu.user_ms\" or r._field == \"systemMetrics.cpu.iowait_ms\" or r._field == \"systemMetrics.cpu.nice_ms\" or r._field == \"systemMetrics.cpu.softirq_ms\" or r._field == \"systemMetrics.cpu.steal_ms\" or r._field == \"systemMetrics.cpu.system_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"systemMetrics.cpu.idle_ms\", \"systemMetrics.cpu.user_ms\", \"systemMetrics.cpu.iowait_ms\", \"systemMetrics.cpu.nice_ms\", \"systemMetrics.cpu.softirq_ms\", \"systemMetrics.cpu.steal_ms\", \"systemMetrics.cpu.system_ms\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      idle_ms: r[\"systemMetrics.cpu.idle_ms\"],\r\n      user_ms: r[\"systemMetrics.cpu.user_ms\"],\r\n      iowait_ms: r[\"systemMetrics.cpu.iowait_ms\"],\r\n      nice_ms: r[\"systemMetrics.cpu.nice_ms\"],\r\n      softirq_ms: r[\"systemMetrics.cpu.softirq_ms\"],\r\n      steal_ms: r[\"systemMetrics.cpu.steal_ms\"],\r\n      system_ms: r[\"systemMetrics.cpu.system_ms\"],\r\n      total_ms: r[\"systemMetrics.cpu.idle_ms\"] + r[\"systemMetrics.cpu.user_ms\"] + r[\"systemMetrics.cpu.iowait_ms\"] + r[\"systemMetrics.cpu.nice_ms\"] + r[\"systemMetrics.cpu.softirq_ms\"] + r[\"systemMetrics.cpu.steal_ms\"] + r[\"systemMetrics.cpu.system_ms\"]\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      user: 100.0 * float(v: r.user_ms) / float(v: r.total_ms),\r\n      system: 100.0 * float(v: r.system_ms) / float(v: r.total_ms),\r\n      iowait: 100.0 * float(v: r.iowait_ms) / float(v: r.total_ms),\r\n  }))\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Disk writes and reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r._field =~ /^systemMetrics\\.disks\\..*\\.writes$/ or r._field =~ /^systemMetrics\\.disks\\..*\\.reads$/)\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.disks.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s)\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.memory.MemAvailable_kb\" or r[\"_field\"] == \"systemMetrics.memory.MemFree_kb\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"systemMetrics.memory.MemAvailable_kb\" then \"available\"\r\n    else if r._field == \"systemMetrics.memory.MemFree_kb\" then \"free\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r._field =~ /^systemMetrics\\.disks\\..*\\.io_in_progress$/ or r._field =~ /^systemMetrics\\.disks\\..*\\.io_queued_ms$/ or r._field =~ /^systemMetrics\\.disks\\..*\\.io_time_ms$/)\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.disks.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    },
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r._field =~ /^systemMetrics\\.disks\\..*\\.io_in_progress$/ )\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.disks.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n\r\n\r\n\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r._field =~ /^systemMetrics\\.disks\\..*\\.write_sectors$/ or r._field =~ /^systemMetrics\\.disks\\..*\\.write_time_ms$/ or r._field =~ /^systemMetrics\\.disks\\..*\\.writes_merged$/)\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.disks.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    },
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r._field =~ /^systemMetrics\\.disks\\..*\\.io_in_progress$/ )\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.disks.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n\r\n\r\n\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.memory.SwapFree_kb\" or r[\"_field\"] == \"systemMetrics.memory.SwapTotal_kb\")\r\n  |> map(fn: (r) => ({r with _field:\r\n    if r._field == \"systemMetrics.memory.SwapFree_kb\" then \"swap free\"\r\n    else if r._field == \"systemMetrics.memory.SwapTotal_kb\" then \"swap total\"\r\n    else r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r._field =~ /^systemMetrics\\.disks\\..*\\.read_sectors$/ or r._field =~ /^systemMetrics\\.disks\\..*\\.read_time_ms$/  or r._field =~ /^systemMetrics\\.disks\\..*\\.reads_merged$/)\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.disks.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    },
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) =>  r._field =~ /^systemMetrics\\.disks\\..*\\.io_in_progress$/ )\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.disks.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n\r\n\r\n\r\n",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "TCP ActiveOpens / AttemptFails / EstabResets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:ActiveOpens\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:AttemptFails\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:EstabResets\")\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.netstat.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "TCP: InSegs / OutSegs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:InSegs\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:OutSegs\")\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.netstat.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "TCP Routing Issues",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Ip:OutNoRoutes\" )\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.netstat.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "TCP Connection Issues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:CurrEstab\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:EstabResets\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:OutRsts\")\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.netstat.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "TCP Packet Loss or Corruption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n |> filter(fn: (r) => r[\"version\"] =~ /^${version:regex}$/)\r\n |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:InCsumErrors\" \r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Tcp:InErrs\"\r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Tcp:RetransSegs\"\r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Ip:InDiscards\"\r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Ip:OutDiscards\")\r\n  |> map(fn: (r) => ({r with _field: strings.trimPrefix(v: r._field, prefix: \"systemMetrics.netstat.\")}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)",
     "legendFormat": "{{_field}}"
    }
   ]
  },
  {
   "title": "Average Operation Latency (µs/op)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^serverStatus\\.opLatencies\\.(reads|writes|commands)\\.(latency|ops)$/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ _time: r._time, read_avg: if r[\"serverStatus.opLatencies.reads.ops\"] > 0 then float(v: r[\"serverStatus.opLatencies.reads.latency\"]) / float(v: r[\"serverStatus.opLatencies.reads.ops\"]) else 0.0, write_avg: if r[\"serverStatus.opLatencies.writes.ops\"] > 0 then float(v: r[\"serverStatus.opLatencies.writes.latency\"]) / float(v: r[\"serverStatus.opLatencies.writes.ops\"]) else 0.0, cmd_avg: if r[\"serverStatus.opLatencies.commands.ops\"] > 0 then float(v: r[\"serverStatus.opLatencies.commands.latency\"]) / float(v: r[\"serverStatus.opLatencies.commands.ops\"]) else 0.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Average Operation Latency (µs/op) [Derived]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /serverStatus\\.opLatencies\\.(reads|writes|commands)\\.(latency|ops)$/)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      read_avg: if r[\"serverStatus.opLatencies.reads.ops\"] > 0 then float(v: r[\"serverStatus.opLatencies.reads.latency\"]) / float(v: r[\"serverStatus.opLatencies.reads.ops\"]) else 0.0,\n      write_avg: if r[\"serverStatus.opLatencies.writes.ops\"] > 0 then float(v: r[\"serverStatus.opLatencies.writes.latency\"]) / float(v: r[\"serverStatus.opLatencies.writes.ops\"]) else 0.0,\n      cmd_avg: if r[\"serverStatus.opLatencies.commands.ops\"] > 0 then float(v: r[\"serverStatus.opLatencies.commands.latency\"]) / float(v: r[\"serverStatus.opLatencies.commands.ops\"]) else 0.0\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}